package com.servicemarket.app.utils.jCountryData

object JCountryData {

    fun getAllCountriesList() = genericCountryList

    fun getSingleCountry(s: String): JCountryListType.JCountry? {
        return genericCountryList.first { it is JCountryListType.JCountry && ( it.alpha2.contains(s,true) || it.alpha3.contains(s,true) || it.countryCode.contains(s,true) ) } as JCountryListType.JCountry?
    }

    val genericCountryList : MutableList<JCountryListType> = mutableListOf(
        JCountryListType.JCountryFirstAlphabet("A"),
        JCountryListType.JCountry(alpha2 = "AF", alpha3 = "AFG", countryCode = "+93", countryName = "Afghanistan", flagUrl = "https://flagcdn.com/w320/af.png"),
        JCountryListType.JCountry(alpha2 = "AL", alpha3 = "ALB", countryCode = "+355", countryName = "Albania", flagUrl = "https://flagcdn.com/w320/al.png"),
        JCountryListType.JCountry(alpha2 = "DZ", alpha3 = "DZA", countryCode = "+213", countryName = "Algeria", flagUrl = "https://flagcdn.com/w320/dz.png"),
        JCountryListType.JCountry(alpha2 = "AS", alpha3 = "ASM", countryCode = "+1 684", countryName = "American Samoa", flagUrl = "https://flagcdn.com/w320/as.png"),
        JCountryListType.JCountry(alpha2 = "AD", alpha3 = "AND", countryCode = "+376", countryName = "Andorra", flagUrl = "https://flagcdn.com/w320/ad.png"),
        JCountryListType.JCountry(alpha2 = "AO", alpha3 = "AGO", countryCode = "+244", countryName = "Angola", flagUrl = "https://flagcdn.com/w320/ao.png"),
        JCountryListType.JCountry(alpha2 = "AI", alpha3 = "AIA", countryCode = "+1 264", countryName = "Anguilla", flagUrl = "https://flagcdn.com/w320/ai.png"),
        JCountryListType.JCountry(alpha2 = "AQ", alpha3 = "ATA", countryCode = "+672, +64", countryName = "Antarctica", flagUrl = "https://flagcdn.com/w320/aq.png"),
        JCountryListType.JCountry(alpha2 = "AG", alpha3 = "ATG", countryCode = "+1 268", countryName = "Antigua and Barbuda", flagUrl = "https://flagcdn.com/w320/ag.png"),
        JCountryListType.JCountry(alpha2 = "AR", alpha3 = "ARG", countryCode = "+54", countryName = "Argentina", flagUrl = "https://flagcdn.com/w320/ar.png"),
        JCountryListType.JCountry(alpha2 = "AM", alpha3 = "ARM", countryCode = "+374", countryName = "Armenia", flagUrl = "https://flagcdn.com/w320/am.png"),
        JCountryListType.JCountry(alpha2 = "AW", alpha3 = "ABW", countryCode = "+297", countryName = "Aruba", flagUrl = "https://flagcdn.com/w320/aw.png"),
        JCountryListType.JCountry(alpha2 = "AU", alpha3 = "AUS", countryCode = "+61", countryName = "Australia", flagUrl = "https://flagcdn.com/w320/au.png"),
        JCountryListType.JCountry(alpha2 = "AT", alpha3 = "AUT", countryCode = "+43", countryName = "Austria", flagUrl = "https://flagcdn.com/w320/at.png"),
        JCountryListType.JCountry(alpha2 = "AZ", alpha3 = "AZE", countryCode = "+994", countryName = "Azerbaijan", flagUrl = "https://flagcdn.com/w320/az.png"),

        JCountryListType.JCountryFirstAlphabet("B"),
        JCountryListType.JCountry(alpha2 = "BS", alpha3 = "BHS", countryCode = "+1 242", countryName = "Bahamas", flagUrl = "https://flagcdn.com/w320/bs.png"),
        JCountryListType.JCountry(alpha2 = "BH", alpha3 = "BHR", countryCode = "+973", countryName = "Bahrain", flagUrl = "https://flagcdn.com/w320/bh.png"),
        JCountryListType.JCountry(alpha2 = "BD", alpha3 = "BGD", countryCode = "+880", countryName = "Bangladesh", flagUrl = "https://flagcdn.com/w320/bd.png"),
        JCountryListType.JCountry(alpha2 = "BB", alpha3 = "BRB", countryCode = "+1 246", countryName = "Barbados", flagUrl = "https://flagcdn.com/w320/bb.png"),
        JCountryListType.JCountry(alpha2 = "BY", alpha3 = "BLR", countryCode = "+375", countryName = "Belarus", flagUrl = "https://flagcdn.com/w320/by.png"),
        JCountryListType.JCountry(alpha2 = "BE", alpha3 = "BEL", countryCode = "+32", countryName = "Belgium", flagUrl = "https://flagcdn.com/w320/be.png"),
        JCountryListType.JCountry(alpha2 = "BZ", alpha3 = "BLZ", countryCode = "+501", countryName = "Belize", flagUrl = "https://flagcdn.com/w320/bz.png"),
        JCountryListType.JCountry(alpha2 = "BJ", alpha3 = "BEN", countryCode = "+229", countryName = "Benin", flagUrl = "https://flagcdn.com/w320/bj.png"),
        JCountryListType.JCountry(alpha2 = "BM", alpha3 = "BMU", countryCode = "+1 441", countryName = "Bermuda", flagUrl = "https://flagcdn.com/w320/bm.png"),
        JCountryListType.JCountry(alpha2 = "BT", alpha3 = "BTN", countryCode = "+975", countryName = "Bhutan", flagUrl = "https://flagcdn.com/w320/bt.png"),
        JCountryListType.JCountry(alpha2 = "BO", alpha3 = "BOL", countryCode = "+591", countryName = "Bolivia", flagUrl = "https://flagcdn.com/w320/bo.png"),
        JCountryListType.JCountry(alpha2 = "BA", alpha3 = "BIH", countryCode = "+387", countryName = "Bosnia and Herzegovina", flagUrl = "https://flagcdn.com/w320/ba.png"),
        JCountryListType.JCountry(alpha2 = "BW", alpha3 = "BWA", countryCode = "+267", countryName = "Botswana", flagUrl = "https://flagcdn.com/w320/bw.png"),
        JCountryListType.JCountry(alpha2 = "BR", alpha3 = "BRA", countryCode = "+55", countryName = "Brazil", flagUrl = "https://flagcdn.com/w320/br.png"),
        JCountryListType.JCountry(alpha2 = "IO", alpha3 = "IOT", countryCode = "+246", countryName = "British Indian Ocean Territory", flagUrl = "https://flagcdn.com/w320/io.png"),
        JCountryListType.JCountry(alpha2 = "VG", alpha3 = "VGB", countryCode = "+1 284", countryName = "British Virgin Islands", flagUrl = "https://flagcdn.com/w320/vg.png"),
        JCountryListType.JCountry(alpha2 = "BN", alpha3 = "BRN", countryCode = "+673", countryName = "Brunei", flagUrl = "https://flagcdn.com/w320/bn.png"),
        JCountryListType.JCountry(alpha2 = "BG", alpha3 = "BGR", countryCode = "+359", countryName = "Bulgaria", flagUrl = "https://flagcdn.com/w320/bg.png"),
        JCountryListType.JCountry(alpha2 = "BF", alpha3 = "BFA", countryCode = "+226", countryName = "Burkina Faso", flagUrl = "https://flagcdn.com/w320/bf.png"),
        JCountryListType.JCountry(alpha2 = "BI", alpha3 = "BDI", countryCode = "+257", countryName = "Burundi", flagUrl = "https://flagcdn.com/w320/bi.png"),

        JCountryListType.JCountryFirstAlphabet("C"),
        JCountryListType.JCountry(alpha2 = "KH", alpha3 = "KHM", countryCode = "+855", countryName = "Cambodia", flagUrl = "https://flagcdn.com/w320/kh.png"),
        JCountryListType.JCountry(alpha2 = "CM", alpha3 = "CMR", countryCode = "+237", countryName = "Cameroon", flagUrl = "https://flagcdn.com/w320/cm.png"),
        JCountryListType.JCountry(alpha2 = "CA", alpha3 = "CAN", countryCode = "+1", countryName = "Canada", flagUrl = "https://flagcdn.com/w320/ca.png"),
        JCountryListType.JCountry(alpha2 = "CV", alpha3 = "CPV", countryCode = "+238", countryName = "Cape Verde", flagUrl = "https://flagcdn.com/w320/cv.png"),
        JCountryListType.JCountry(alpha2 = "KY", alpha3 = "CYM", countryCode = "+1 345", countryName = "Cayman Islands", flagUrl = "https://flagcdn.com/w320/ky.png"),
        JCountryListType.JCountry(alpha2 = "CF", alpha3 = "CAF", countryCode = "+236", countryName = "Central African Republic", flagUrl = "https://flagcdn.com/w320/cf.png"),
        JCountryListType.JCountry(alpha2 = "TD", alpha3 = "TCD", countryCode = "+235", countryName = "Chad", flagUrl = "https://flagcdn.com/w320/td.png"),
        JCountryListType.JCountry(alpha2 = "CL", alpha3 = "CHL", countryCode = "+56", countryName = "Chile", flagUrl = "https://flagcdn.com/w320/cl.png"),
        JCountryListType.JCountry(alpha2 = "CN", alpha3 = "CHN", countryCode = "+86", countryName = "China", flagUrl = "https://flagcdn.com/w320/cn.png"),
        JCountryListType.JCountry(alpha2 = "CX", alpha3 = "CXR", countryCode = "+61", countryName = "Christmas Island", flagUrl = "https://flagcdn.com/w320/cx.png"),
        JCountryListType.JCountry(alpha2 = "CC", alpha3 = "CCK", countryCode = "+61", countryName = "Cocos (Keeling) Islands", flagUrl = "https://flagcdn.com/w320/cc.png"),
        JCountryListType.JCountry(alpha2 = "CO", alpha3 = "COL", countryCode = "+57", countryName = "Colombia", flagUrl = "https://flagcdn.com/w320/co.png"),
        JCountryListType.JCountry(alpha2 = "KM", alpha3 = "COM", countryCode = "+269", countryName = "Comoros", flagUrl = "https://flagcdn.com/w320/km.png"),
        JCountryListType.JCountry(alpha2 = "CG", alpha3 = "COG", countryCode = "+242", countryName = "Congo", flagUrl = "https://flagcdn.com/w320/cg.png"),
        JCountryListType.JCountry(alpha2 = "CK", alpha3 = "COK", countryCode = "+682", countryName = "Cook Islands", flagUrl = "https://flagcdn.com/w320/ck.png"),
        JCountryListType.JCountry(alpha2 = "CR", alpha3 = "CRC", countryCode = "+506", countryName = "Costa Rica", flagUrl = "https://flagcdn.com/w320/cr.png"),
        JCountryListType.JCountry(alpha2 = "HR", alpha3 = "HRV", countryCode = "+385", countryName = "Croatia", flagUrl = "https://flagcdn.com/w320/hr.png"),
        JCountryListType.JCountry(alpha2 = "CU", alpha3 = "CUB", countryCode = "+53", countryName = "Cuba", flagUrl = "https://flagcdn.com/w320/cu.png"),
        JCountryListType.JCountry(alpha2 = "CY", alpha3 = "CYP", countryCode = "+357", countryName = "Cyprus", flagUrl = "https://flagcdn.com/w320/cy.png"),
        JCountryListType.JCountry(alpha2 = "CZ", alpha3 = "CZE", countryCode = "+420", countryName = "Czech Republic", flagUrl = "https://flagcdn.com/w320/cz.png"),

        JCountryListType.JCountryFirstAlphabet("D"),
        JCountryListType.JCountry(alpha2 = "CD", alpha3 = "COD", countryCode = "+243", countryName = "Democratic Republic of the Congo", flagUrl = "https://flagcdn.com/w320/cd.png"),
        JCountryListType.JCountry(alpha2 = "DK", alpha3 = "DNK", countryCode = "+45", countryName = "Denmark", flagUrl = "https://flagcdn.com/w320/dk.png"),
        JCountryListType.JCountry(alpha2 = "DJ", alpha3 = "DJI", countryCode = "+253", countryName = "Djibouti", flagUrl = "https://flagcdn.com/w320/dj.png"),
        JCountryListType.JCountry(alpha2 = "DM", alpha3 = "DMA", countryCode = "+1 767", countryName = "Dominica", flagUrl = "https://flagcdn.com/w320/dm.png"),
        JCountryListType.JCountry(alpha2 = "DO", alpha3 = "DOM", countryCode = "+1 809, +1 829, +1 849", countryName = "Dominican Republic", flagUrl = "https://flagcdn.com/w320/do.png"),

        JCountryListType.JCountryFirstAlphabet("E"),
        JCountryListType.JCountry(alpha2 = "EC", alpha3 = "ECU", countryCode = "+593", countryName = "Ecuador", flagUrl = "https://flagcdn.com/w320/ec.png"),
        JCountryListType.JCountry(alpha2 = "EG", alpha3 = "EGY", countryCode = "+20", countryName = "Egypt", flagUrl = "https://flagcdn.com/w320/eg.png"),
        JCountryListType.JCountry(alpha2 = "SV", alpha3 = "SLV", countryCode = "+503", countryName = "El Salvador", flagUrl = "https://flagcdn.com/w320/sv.png"),
        JCountryListType.JCountry(alpha2 = "GQ", alpha3 = "GNQ", countryCode = "+240", countryName = "Equatorial Guinea", flagUrl = "https://flagcdn.com/w320/gq.png"),
        JCountryListType.JCountry(alpha2 = "ER", alpha3 = "ERI", countryCode = "+291", countryName = "Eritrea", flagUrl = "https://flagcdn.com/w320/er.png"),
        JCountryListType.JCountry(alpha2 = "EE", alpha3 = "EST", countryCode = "+372", countryName = "Estonia", flagUrl = "https://flagcdn.com/w320/ee.png"),
        JCountryListType.JCountry(alpha2 = "ET", alpha3 = "ETH", countryCode = "+251", countryName = "Ethiopia", flagUrl = "https://flagcdn.com/w320/et.png"),

        JCountryListType.JCountryFirstAlphabet("F"),
        JCountryListType.JCountry(alpha2 = "FK", alpha3 = "FLK", countryCode = "+500", countryName = "Falkland Islands", flagUrl = "https://flagcdn.com/w320/fk.png"),
        JCountryListType.JCountry(alpha2 = "FO", alpha3 = "FRO", countryCode = "+298", countryName = "Faroe Islands", flagUrl = "https://flagcdn.com/w320/fo.png"),
        JCountryListType.JCountry(alpha2 = "FJ", alpha3 = "FJI", countryCode = "+679", countryName = "Fiji", flagUrl = "https://flagcdn.com/w320/fj.png"),
        JCountryListType.JCountry(alpha2 = "FI", alpha3 = "FIN", countryCode = "+358", countryName = "Finland", flagUrl = "https://flagcdn.com/w320/fi.png"),
        JCountryListType.JCountry(alpha2 = "FR", alpha3 = "FRA", countryCode = "+33", countryName = "France", flagUrl = "https://flagcdn.com/w320/fr.png"),
        JCountryListType.JCountry(alpha2 = "GF", alpha3 = "GUF", countryCode = "+594", countryName = "French Guiana", flagUrl = "https://flagcdn.com/w320/gf.png"),
        JCountryListType.JCountry(alpha2 = "PF", alpha3 = "PYF", countryCode = "+689", countryName = "French Polynesia", flagUrl = "https://flagcdn.com/w320/pf.png"),

        JCountryListType.JCountryFirstAlphabet("G"),
        JCountryListType.JCountry(alpha2 = "GA", alpha3 = "GAB", countryCode = "+241", countryName = "Gabon", flagUrl = "https://flagcdn.com/w320/ga.png"),
        JCountryListType.JCountry(alpha2 = "GM", alpha3 = "GMB", countryCode = "+220", countryName = "Gambia", flagUrl = "https://flagcdn.com/w320/gm.png"),
        JCountryListType.JCountry(alpha2 = "GE", alpha3 = "GEO", countryCode = "+995", countryName = "Georgia", flagUrl = "https://flagcdn.com/w320/ge.png"),
        JCountryListType.JCountry(alpha2 = "DE", alpha3 = "DEU", countryCode = "+49", countryName = "Germany", flagUrl = "https://flagcdn.com/w320/de.png"),
        JCountryListType.JCountry(alpha2 = "GH", alpha3 = "GHA", countryCode = "+233", countryName = "Ghana", flagUrl = "https://flagcdn.com/w320/gh.png"),
        JCountryListType.JCountry(alpha2 = "GI", alpha3 = "GIB", countryCode = "+350", countryName = "Gibraltar", flagUrl = "https://flagcdn.com/w320/gi.png"),
        JCountryListType.JCountry(alpha2 = "GR", alpha3 = "GRC", countryCode = "+30", countryName = "Greece", flagUrl = "https://flagcdn.com/w320/gr.png"),
        JCountryListType.JCountry(alpha2 = "GL", alpha3 = "GRL", countryCode = "+299", countryName = "Greenland", flagUrl = "https://flagcdn.com/w320/gl.png"),
        JCountryListType.JCountry(alpha2 = "GD", alpha3 = "GRD", countryCode = "+1 473", countryName = "Grenada", flagUrl = "https://flagcdn.com/w320/gd.png"),
        JCountryListType.JCountry(alpha2 = "GP", alpha3 = "GLP", countryCode = "+590", countryName = "Guadeloupe", flagUrl = "https://flagcdn.com/w320/gp.png"),
        JCountryListType.JCountry(alpha2 = "GU", alpha3 = "GUM", countryCode = "+1 671", countryName = "Guam", flagUrl = "https://flagcdn.com/w320/gu.png"),
        JCountryListType.JCountry(alpha2 = "GT", alpha3 = "GTM", countryCode = "+502", countryName = "Guatemala", flagUrl = "https://flagcdn.com/w320/gt.png"),
        JCountryListType.JCountry(alpha2 = "GG", alpha3 = "GGY", countryCode = "+44", countryName = "Guernsey", flagUrl = "https://flagcdn.com/w320/gg.png"),
        JCountryListType.JCountry(alpha2 = "GN", alpha3 = "GIN", countryCode = "+224", countryName = "Guinea", flagUrl = "https://flagcdn.com/w320/gn.png"),
        JCountryListType.JCountry(alpha2 = "GW", alpha3 = "GNB", countryCode = "+245", countryName = "Guinea-Bissau", flagUrl = "https://flagcdn.com/w320/gw.png"),
        JCountryListType.JCountry(alpha2 = "GY", alpha3 = "GUY", countryCode = "+592", countryName = "Guyana", flagUrl = "https://flagcdn.com/w320/gy.png"),

        JCountryListType.JCountryFirstAlphabet("H"),
        JCountryListType.JCountry(alpha2 = "HT", alpha3 = "HTI", countryCode = "+509", countryName = "Haiti", flagUrl = "https://flagcdn.com/w320/ht.png"),
        JCountryListType.JCountry(alpha2 = "HN", alpha3 = "HND", countryCode = "+504", countryName = "Honduras", flagUrl = "https://flagcdn.com/w320/hn.png"),
        JCountryListType.JCountry(alpha2 = "HK", alpha3 = "HKG", countryCode = "+852", countryName = "Hong Kong", flagUrl = "https://flagcdn.com/w320/hk.png"),
        JCountryListType.JCountry(alpha2 = "HU", alpha3 = "HUN", countryCode = "+36", countryName = "Hungary", flagUrl = "https://flagcdn.com/w320/hu.png"),

        JCountryListType.JCountryFirstAlphabet("I"),
        JCountryListType.JCountry(alpha2 = "IS", alpha3 = "ISL", countryCode = "+354", countryName = "Iceland", flagUrl = "https://flagcdn.com/w320/is.png"),
        JCountryListType.JCountry(alpha2 = "IN", alpha3 = "IND", countryCode = "+91", countryName = "India", flagUrl = "https://flagcdn.com/w320/in.png"),
        JCountryListType.JCountry(alpha2 = "ID", alpha3 = "IDN", countryCode = "+62", countryName = "Indonesia", flagUrl = "https://flagcdn.com/w320/id.png"),
        JCountryListType.JCountry(alpha2 = "IR", alpha3 = "IRN", countryCode = "+98", countryName = "Iran", flagUrl = "https://flagcdn.com/w320/ir.png"),
        JCountryListType.JCountry(alpha2 = "IQ", alpha3 = "IRQ", countryCode = "+964", countryName = "Iraq", flagUrl = "https://flagcdn.com/w320/iq.png"),
        JCountryListType.JCountry(alpha2 = "IE", alpha3 = "IRL", countryCode = "+353", countryName = "Ireland", flagUrl = "https://flagcdn.com/w320/ie.png"),
        JCountryListType.JCountry(alpha2 = "IM", alpha3 = "IMN", countryCode = "+44", countryName = "Isle of Man", flagUrl = "https://flagcdn.com/w320/im.png"),
        JCountryListType.JCountry(alpha2 = "IL", alpha3 = "ISR", countryCode = "+972", countryName = "Israel", flagUrl = "https://flagcdn.com/w320/il.png"),
        JCountryListType.JCountry(alpha2 = "IT", alpha3 = "ITA", countryCode = "+39", countryName = "Italy", flagUrl = "https://flagcdn.com/w320/it.png"),

        JCountryListType.JCountryFirstAlphabet("J"),
        JCountryListType.JCountry(alpha2 = "JM", alpha3 = "JAM", countryCode = "+1 876", countryName = "Jamaica", flagUrl = "https://flagcdn.com/w320/jm.png"),
        JCountryListType.JCountry(alpha2 = "JP", alpha3 = "JPN", countryCode = "+81", countryName = "Japan", flagUrl = "https://flagcdn.com/w320/jp.png"),
        JCountryListType.JCountry(alpha2 = "JE", alpha3 = "JEY", countryCode = "+44", countryName = "Jersey", flagUrl = "https://flagcdn.com/w320/je.png"),
        JCountryListType.JCountry(alpha2 = "JO", alpha3 = "JOR", countryCode = "+962", countryName = "Jordan", flagUrl = "https://flagcdn.com/w320/jo.png"),

        JCountryListType.JCountryFirstAlphabet("K"),
        JCountryListType.JCountry(alpha2 = "KZ", alpha3 = "KAZ", countryCode = "+7", countryName = "Kazakhstan", flagUrl = "https://flagcdn.com/w320/kz.png"),
        JCountryListType.JCountry(alpha2 = "KE", alpha3 = "KEN", countryCode = "+254", countryName = "Kenya", flagUrl = "https://flagcdn.com/w320/ke.png"),
        JCountryListType.JCountry(alpha2 = "KI", alpha3 = "KIR", countryCode = "+686", countryName = "Kiribati", flagUrl = "https://flagcdn.com/w320/ki.png"),
        JCountryListType.JCountry(alpha2 = "KP", alpha3 = "PRK", countryCode = "+850", countryName = "North Korea", flagUrl = "https://flagcdn.com/w320/kp.png"),
        JCountryListType.JCountry(alpha2 = "KR", alpha3 = "KOR", countryCode = "+82", countryName = "South Korea", flagUrl = "https://flagcdn.com/w320/kr.png"),
        JCountryListType.JCountry(alpha2 = "KW", alpha3 = "KWT", countryCode = "+965", countryName = "Kuwait", flagUrl = "https://flagcdn.com/w320/kw.png"),
        JCountryListType.JCountry(alpha2 = "KG", alpha3 = "KGZ", countryCode = "+996", countryName = "Kyrgyzstan", flagUrl = "https://flagcdn.com/w320/kg.png"),

        JCountryListType.JCountryFirstAlphabet("L"),
        JCountryListType.JCountry(alpha2 = "LA", alpha3 = "LAO", countryCode = "+856", countryName = "Laos", flagUrl = "https://flagcdn.com/w320/la.png"),
        JCountryListType.JCountry(alpha2 = "LV", alpha3 = "LVA", countryCode = "+371", countryName = "Latvia", flagUrl = "https://flagcdn.com/w320/lv.png"),
        JCountryListType.JCountry(alpha2 = "LB", alpha3 = "LBN", countryCode = "+961", countryName = "Lebanon", flagUrl = "https://flagcdn.com/w320/lb.png"),
        JCountryListType.JCountry(alpha2 = "LS", alpha3 = "LSO", countryCode = "+266", countryName = "Lesotho", flagUrl = "https://flagcdn.com/w320/ls.png"),
        JCountryListType.JCountry(alpha2 = "LR", alpha3 = "LBR", countryCode = "+231", countryName = "Liberia", flagUrl = "https://flagcdn.com/w320/lr.png"),
        JCountryListType.JCountry(alpha2 = "LY", alpha3 = "LBY", countryCode = "+218", countryName = "Libya", flagUrl = "https://flagcdn.com/w320/ly.png"),
        JCountryListType.JCountry(alpha2 = "LI", alpha3 = "LIE", countryCode = "+423", countryName = "Liechtenstein", flagUrl = "https://flagcdn.com/w320/li.png"),
        JCountryListType.JCountry(alpha2 = "LT", alpha3 = "LTU", countryCode = "+370", countryName = "Lithuania", flagUrl = "https://flagcdn.com/w320/lt.png"),
        JCountryListType.JCountry(alpha2 = "LU", alpha3 = "LUX", countryCode = "+352", countryName = "Luxembourg", flagUrl = "https://flagcdn.com/w320/lu.png"),

        JCountryListType.JCountryFirstAlphabet("M"),
        JCountryListType.JCountry(alpha2 = "MO", alpha3 = "MAC", countryCode = "+853", countryName = "Macau", flagUrl = "https://flagcdn.com/w320/mo.png"),
        JCountryListType.JCountry(alpha2 = "MK", alpha3 = "MKD", countryCode = "+389", countryName = "North Macedonia", flagUrl = "https://flagcdn.com/w320/mk.png"),
        JCountryListType.JCountry(alpha2 = "MG", alpha3 = "MDG", countryCode = "+261", countryName = "Madagascar", flagUrl = "https://flagcdn.com/w320/mg.png"),
        JCountryListType.JCountry(alpha2 = "MW", alpha3 = "MWI", countryCode = "+265", countryName = "Malawi", flagUrl = "https://flagcdn.com/w320/mw.png"),
        JCountryListType.JCountry(alpha2 = "MY", alpha3 = "MYS", countryCode = "+60", countryName = "Malaysia", flagUrl = "https://flagcdn.com/w320/my.png"),
        JCountryListType.JCountry(alpha2 = "MV", alpha3 = "MDV", countryCode = "+960", countryName = "Maldives", flagUrl = "https://flagcdn.com/w320/mv.png"),
        JCountryListType.JCountry(alpha2 = "ML", alpha3 = "MLI", countryCode = "+223", countryName = "Mali", flagUrl = "https://flagcdn.com/w320/ml.png"),
        JCountryListType.JCountry(alpha2 = "MT", alpha3 = "MLT", countryCode = "+356", countryName = "Malta", flagUrl = "https://flagcdn.com/w320/mt.png"),
        JCountryListType.JCountry(alpha2 = "MH", alpha3 = "MHL", countryCode = "+692", countryName = "Marshall Islands", flagUrl = "https://flagcdn.com/w320/mh.png"),
        JCountryListType.JCountry(alpha2 = "MQ", alpha3 = "MTQ", countryCode = "+596", countryName = "Martinique", flagUrl = "https://flagcdn.com/w320/mq.png"),
        JCountryListType.JCountry(alpha2 = "MR", alpha3 = "MRT", countryCode = "+222", countryName = "Mauritania", flagUrl = "https://flagcdn.com/w320/mr.png"),
        JCountryListType.JCountry(alpha2 = "MU", alpha3 = "MUS", countryCode = "+230", countryName = "Mauritius", flagUrl = "https://flagcdn.com/w320/mu.png"),
        JCountryListType.JCountry(alpha2 = "YT", alpha3 = "MYT", countryCode = "+262", countryName = "Mayotte", flagUrl = "https://flagcdn.com/w320/yt.png"),
        JCountryListType.JCountry(alpha2 = "MX", alpha3 = "MEX", countryCode = "+52", countryName = "Mexico", flagUrl = "https://flagcdn.com/w320/mx.png"),
        JCountryListType.JCountry(alpha2 = "FM", alpha3 = "FSM", countryCode = "+691", countryName = "Micronesia", flagUrl = "https://flagcdn.com/w320/fm.png"),
        JCountryListType.JCountry(alpha2 = "MD", alpha3 = "MDA", countryCode = "+373", countryName = "Moldova", flagUrl = "https://flagcdn.com/w320/md.png"),
        JCountryListType.JCountry(alpha2 = "MC", alpha3 = "MCO", countryCode = "+377", countryName = "Monaco", flagUrl = "https://flagcdn.com/w320/mc.png"),
        JCountryListType.JCountry(alpha2 = "MN", alpha3 = "MNG", countryCode = "+976", countryName = "Mongolia", flagUrl = "https://flagcdn.com/w320/mn.png"),
        JCountryListType.JCountry(alpha2 = "ME", alpha3 = "MNE", countryCode = "+382", countryName = "Montenegro", flagUrl = "https://flagcdn.com/w320/me.png"),
        JCountryListType.JCountry(alpha2 = "MS", alpha3 = "MSR", countryCode = "+1 664", countryName = "Montserrat", flagUrl = "https://flagcdn.com/w320/ms.png"),
        JCountryListType.JCountry(alpha2 = "MA", alpha3 = "MAR", countryCode = "+212", countryName = "Morocco", flagUrl = "https://flagcdn.com/w320/ma.png"),
        JCountryListType.JCountry(alpha2 = "MZ", alpha3 = "MOZ", countryCode = "+258", countryName = "Mozambique", flagUrl = "https://flagcdn.com/w320/mz.png"),
        JCountryListType.JCountry(alpha2 = "MM", alpha3 = "MMR", countryCode = "+95", countryName = "Myanmar", flagUrl = "https://flagcdn.com/w320/mm.png"),

        JCountryListType.JCountryFirstAlphabet("N"),
        JCountryListType.JCountry(alpha2 = "NA", alpha3 = "NAM", countryCode = "+264", countryName = "Namibia", flagUrl = "https://flagcdn.com/w320/na.png"),
        JCountryListType.JCountry(alpha2 = "NR", alpha3 = "NRU", countryCode = "+674", countryName = "Nauru", flagUrl = "https://flagcdn.com/w320/nr.png"),
        JCountryListType.JCountry(alpha2 = "NP", alpha3 = "NPL", countryCode = "+977", countryName = "Nepal", flagUrl = "https://flagcdn.com/w320/np.png"),
        JCountryListType.JCountry(alpha2 = "NL", alpha3 = "NLD", countryCode = "+31", countryName = "Netherlands", flagUrl = "https://flagcdn.com/w320/nl.png"),
        JCountryListType.JCountry(alpha2 = "NC", alpha3 = "NCL", countryCode = "+687", countryName = "New Caledonia", flagUrl = "https://flagcdn.com/w320/nc.png"),
        JCountryListType.JCountry(alpha2 = "NZ", alpha3 = "NZL", countryCode = "+64", countryName = "New Zealand", flagUrl = "https://flagcdn.com/w320/nz.png"),
        JCountryListType.JCountry(alpha2 = "NI", alpha3 = "NIC", countryCode = "+505", countryName = "Nicaragua", flagUrl = "https://flagcdn.com/w320/ni.png"),
        JCountryListType.JCountry(alpha2 = "NE", alpha3 = "NER", countryCode = "+227", countryName = "Niger", flagUrl = "https://flagcdn.com/w320/ne.png"),
        JCountryListType.JCountry(alpha2 = "NG", alpha3 = "NGA", countryCode = "+234", countryName = "Nigeria", flagUrl = "https://flagcdn.com/w320/ng.png"),
        JCountryListType.JCountry(alpha2 = "NU", alpha3 = "NIU", countryCode = "+683", countryName = "Niue", flagUrl = "https://flagcdn.com/w320/nu.png"),
        JCountryListType.JCountry(alpha2 = "NF", alpha3 = "NFK", countryCode = "+672", countryName = "Norfolk Island", flagUrl = "https://flagcdn.com/w320/nf.png"),
        JCountryListType.JCountry(alpha2 = "MP", alpha3 = "MNP", countryCode = "+1 670", countryName = "Northern Mariana Islands", flagUrl = "https://flagcdn.com/w320/mp.png"),
        JCountryListType.JCountry(alpha2 = "NO", alpha3 = "NOR", countryCode = "+47", countryName = "Norway", flagUrl = "https://flagcdn.com/w320/no.png"),


        JCountryListType.JCountryFirstAlphabet("O"),
        JCountryListType.JCountry(alpha2 = "OM", alpha3 = "OMN", countryCode = "+968", countryName = "Oman", flagUrl = "https://flagcdn.com/w320/om.png"),


        JCountryListType.JCountryFirstAlphabet("P"),
        JCountryListType.JCountry(alpha2 = "PK", alpha3 = "PAK", countryCode = "+92", countryName = "Pakistan", flagUrl = "https://flagcdn.com/w320/pk.png"),
        JCountryListType.JCountry(alpha2 = "PW", alpha3 = "PLW", countryCode = "+680", countryName = "Palau", flagUrl = "https://flagcdn.com/w320/pw.png"),
        JCountryListType.JCountry(alpha2 = "PS", alpha3 = "PSE", countryCode = "+970", countryName = "Palestine", flagUrl = "https://flagcdn.com/w320/ps.png"),
        JCountryListType.JCountry(alpha2 = "PA", alpha3 = "PAN", countryCode = "+507", countryName = "Panama", flagUrl = "https://flagcdn.com/w320/pa.png"),
        JCountryListType.JCountry(alpha2 = "PG", alpha3 = "PNG", countryCode = "+675", countryName = "Papua New Guinea", flagUrl = "https://flagcdn.com/w320/pg.png"),
        JCountryListType.JCountry(alpha2 = "PY", alpha3 = "PRY", countryCode = "+595", countryName = "Paraguay", flagUrl = "https://flagcdn.com/w320/py.png"),
        JCountryListType.JCountry(alpha2 = "PE", alpha3 = "PER", countryCode = "+51", countryName = "Peru", flagUrl = "https://flagcdn.com/w320/pe.png"),
        JCountryListType.JCountry(alpha2 = "PH", alpha3 = "PHL", countryCode = "+63", countryName = "Philippines", flagUrl = "https://flagcdn.com/w320/ph.png"),
        JCountryListType.JCountry(alpha2 = "PN", alpha3 = "PCN", countryCode = "+870", countryName = "Pitcairn Islands", flagUrl = "https://flagcdn.com/w320/pn.png"),
        JCountryListType.JCountry(alpha2 = "PL", alpha3 = "POL", countryCode = "+48", countryName = "Poland", flagUrl = "https://flagcdn.com/w320/pl.png"),
        JCountryListType.JCountry(alpha2 = "PT", alpha3 = "PRT", countryCode = "+351", countryName = "Portugal", flagUrl = "https://flagcdn.com/w320/pt.png"),
        JCountryListType.JCountry(alpha2 = "PR", alpha3 = "PRI", countryCode = "+1 787, +1 939", countryName = "Puerto Rico", flagUrl = "https://flagcdn.com/w320/pr.png"),

        JCountryListType.JCountryFirstAlphabet("Q"),
        JCountryListType.JCountry(alpha2 = "QA", alpha3 = "QAT", countryCode = "+974", countryName = "Qatar", flagUrl = "https://flagcdn.com/w320/qa.png"),

        JCountryListType.JCountryFirstAlphabet("R"),
        JCountryListType.JCountry(alpha2 = "RE", alpha3 = "REU", countryCode = "+262", countryName = "Réunion", flagUrl = "https://flagcdn.com/w320/re.png"),
        JCountryListType.JCountry(alpha2 = "RO", alpha3 = "ROU", countryCode = "+40", countryName = "Romania", flagUrl = "https://flagcdn.com/w320/ro.png"),
        JCountryListType.JCountry(alpha2 = "RU", alpha3 = "RUS", countryCode = "+7", countryName = "Russia", flagUrl = "https://flagcdn.com/w320/ru.png"),
        JCountryListType.JCountry(alpha2 = "RW", alpha3 = "RWA", countryCode = "+250", countryName = "Rwanda", flagUrl = "https://flagcdn.com/w320/rw.png"),

        JCountryListType.JCountryFirstAlphabet("S"),
        JCountryListType.JCountry(alpha2 = "BL", alpha3 = "BLM", countryCode = "+590", countryName = "Saint Barthélemy", flagUrl = "https://flagcdn.com/w320/bl.png"),
        JCountryListType.JCountry(alpha2 = "SH", alpha3 = "SHN", countryCode = "+290", countryName = "Saint Helena", flagUrl = "https://flagcdn.com/w320/sh.png"),
        JCountryListType.JCountry(alpha2 = "KN", alpha3 = "KNA", countryCode = "+1 869", countryName = "Saint Kitts and Nevis", flagUrl = "https://flagcdn.com/w320/kn.png"),
        JCountryListType.JCountry(alpha2 = "LC", alpha3 = "LCA", countryCode = "+1 758", countryName = "Saint Lucia", flagUrl = "https://flagcdn.com/w320/lc.png"),
        JCountryListType.JCountry(alpha2 = "MF", alpha3 = "MAF", countryCode = "+590", countryName = "Saint Martin", flagUrl = "https://flagcdn.com/w320/mf.png"),
        JCountryListType.JCountry(alpha2 = "PM", alpha3 = "SPM", countryCode = "+508", countryName = "Saint Pierre and Miquelon", flagUrl = "https://flagcdn.com/w320/pm.png"),
        JCountryListType.JCountry(alpha2 = "VC", alpha3 = "VCT", countryCode = "+1 784", countryName = "Saint Vincent and the Grenadines", flagUrl = "https://flagcdn.com/w320/vc.png"),
        JCountryListType.JCountry(alpha2 = "WS", alpha3 = "WSM", countryCode = "+685", countryName = "Samoa", flagUrl = "https://flagcdn.com/w320/ws.png"),
        JCountryListType.JCountry(alpha2 = "SM", alpha3 = "SMR", countryCode = "+378", countryName = "San Marino", flagUrl = "https://flagcdn.com/w320/sm.png"),
        JCountryListType.JCountry(alpha2 = "ST", alpha3 = "STP", countryCode = "+239", countryName = "São Tomé and Príncipe", flagUrl = "https://flagcdn.com/w320/st.png"),
        JCountryListType.JCountry(alpha2 = "SA", alpha3 = "SAU", countryCode = "+966", countryName = "Saudi Arabia", flagUrl = "https://flagcdn.com/w320/sa.png"),
        JCountryListType.JCountry(alpha2 = "SN", alpha3 = "SEN", countryCode = "+221", countryName = "Senegal", flagUrl = "https://flagcdn.com/w320/sn.png"),
        JCountryListType.JCountry(alpha2 = "RS", alpha3 = "SRB", countryCode = "+381", countryName = "Serbia", flagUrl = "https://flagcdn.com/w320/rs.png"),
        JCountryListType.JCountry(alpha2 = "SC", alpha3 = "SYC", countryCode = "+248", countryName = "Seychelles", flagUrl = "https://flagcdn.com/w320/sc.png"),
        JCountryListType.JCountry(alpha2 = "SL", alpha3 = "SLE", countryCode = "+232", countryName = "Sierra Leone", flagUrl = "https://flagcdn.com/w320/sl.png"),
        JCountryListType.JCountry(alpha2 = "SG", alpha3 = "SGP", countryCode = "+65", countryName = "Singapore", flagUrl = "https://flagcdn.com/w320/sg.png"),
        JCountryListType.JCountry(alpha2 = "SX", alpha3 = "SXM", countryCode = "+1 721", countryName = "Sint Maarten", flagUrl = "https://flagcdn.com/w320/sx.png"),
        JCountryListType.JCountry(alpha2 = "SK", alpha3 = "SVK", countryCode = "+421", countryName = "Slovakia", flagUrl = "https://flagcdn.com/w320/sk.png"),
        JCountryListType.JCountry(alpha2 = "SI", alpha3 = "SVN", countryCode = "+386", countryName = "Slovenia", flagUrl = "https://flagcdn.com/w320/si.png"),
        JCountryListType.JCountry(alpha2 = "SB", alpha3 = "SLB", countryCode = "+677", countryName = "Solomon Islands", flagUrl = "https://flagcdn.com/w320/sb.png"),
        JCountryListType.JCountry(alpha2 = "SO", alpha3 = "SOM", countryCode = "+252", countryName = "Somalia", flagUrl = "https://flagcdn.com/w320/so.png"),
        JCountryListType.JCountry(alpha2 = "ZA", alpha3 = "ZAF", countryCode = "+27", countryName = "South Africa", flagUrl = "https://flagcdn.com/w320/za.png"),
        JCountryListType.JCountry(alpha2 = "GS", alpha3 = "SGS", countryCode = "+500", countryName = "South Georgia and the South Sandwich Islands", flagUrl = "https://flagcdn.com/w320/gs.png"),
        JCountryListType.JCountry(alpha2 = "SS", alpha3 = "SSD", countryCode = "+211", countryName = "South Sudan", flagUrl = "https://flagcdn.com/w320/ss.png"),
        JCountryListType.JCountry(alpha2 = "ES", alpha3 = "ESP", countryCode = "+34", countryName = "Spain", flagUrl = "https://flagcdn.com/w320/es.png"),
        JCountryListType.JCountry(alpha2 = "LK", alpha3 = "LKA", countryCode = "+94", countryName = "Sri Lanka", flagUrl = "https://flagcdn.com/w320/lk.png"),
        JCountryListType.JCountry(alpha2 = "SD", alpha3 = "SDN", countryCode = "+249", countryName = "Sudan", flagUrl = "https://flagcdn.com/w320/sd.png"),
        JCountryListType.JCountry(alpha2 = "SR", alpha3 = "SUR", countryCode = "+597", countryName = "Suriname", flagUrl = "https://flagcdn.com/w320/sr.png"),
        JCountryListType.JCountry(alpha2 = "SJ", alpha3 = "SJM", countryCode = "+47", countryName = "Svalbard and Jan Mayen", flagUrl = "https://flagcdn.com/w320/sj.png"),
        JCountryListType.JCountry(alpha2 = "SZ", alpha3 = "SWZ", countryCode = "+268", countryName = "Eswatini", flagUrl = "https://flagcdn.com/w320/sz.png"),
        JCountryListType.JCountry(alpha2 = "SE", alpha3 = "SWE", countryCode = "+46", countryName = "Sweden", flagUrl = "https://flagcdn.com/w320/se.png"),
        JCountryListType.JCountry(alpha2 = "CH", alpha3 = "CHE", countryCode = "+41", countryName = "Switzerland", flagUrl = "https://flagcdn.com/w320/ch.png"),
        JCountryListType.JCountry(alpha2 = "SY", alpha3 = "SYR", countryCode = "+963", countryName = "Syria", flagUrl = "https://flagcdn.com/w320/sy.png"),


        JCountryListType.JCountryFirstAlphabet("T"),
        JCountryListType.JCountry(alpha2 = "TW", alpha3 = "TWN", countryCode = "+886", countryName = "Taiwan", flagUrl = "https://flagcdn.com/w320/tw.png"),
        JCountryListType.JCountry(alpha2 = "TJ", alpha3 = "TJK", countryCode = "+992", countryName = "Tajikistan", flagUrl = "https://flagcdn.com/w320/tj.png"),
        JCountryListType.JCountry(alpha2 = "TZ", alpha3 = "TZA", countryCode = "+255", countryName = "Tanzania", flagUrl = "https://flagcdn.com/w320/tz.png"),
        JCountryListType.JCountry(alpha2 = "TH", alpha3 = "THA", countryCode = "+66", countryName = "Thailand", flagUrl = "https://flagcdn.com/w320/th.png"),
        JCountryListType.JCountry(alpha2 = "TL", alpha3 = "TLS", countryCode = "+670", countryName = "Timor-Leste", flagUrl = "https://flagcdn.com/w320/tl.png"),
        JCountryListType.JCountry(alpha2 = "TG", alpha3 = "TGO", countryCode = "+228", countryName = "Togo", flagUrl = "https://flagcdn.com/w320/tg.png"),
        JCountryListType.JCountry(alpha2 = "TK", alpha3 = "TKL", countryCode = "+690", countryName = "Tokelau", flagUrl = "https://flagcdn.com/w320/tk.png"),
        JCountryListType.JCountry(alpha2 = "TO", alpha3 = "TON", countryCode = "+676", countryName = "Tonga", flagUrl = "https://flagcdn.com/w320/to.png"),
        JCountryListType.JCountry(alpha2 = "TT", alpha3 = "TTO", countryCode = "+1 868", countryName = "Trinidad and Tobago", flagUrl = "https://flagcdn.com/w320/tt.png"),
        JCountryListType.JCountry(alpha2 = "TN", alpha3 = "TUN", countryCode = "+216", countryName = "Tunisia", flagUrl = "https://flagcdn.com/w320/tn.png"),
        JCountryListType.JCountry(alpha2 = "TR", alpha3 = "TUR", countryCode = "+90", countryName = "Turkey", flagUrl = "https://flagcdn.com/w320/tr.png"),
        JCountryListType.JCountry(alpha2 = "TM", alpha3 = "TKM", countryCode = "+993", countryName = "Turkmenistan", flagUrl = "https://flagcdn.com/w320/tm.png"),
        JCountryListType.JCountry(alpha2 = "TC", alpha3 = "TCA", countryCode = "+1 649", countryName = "Turks and Caicos Islands", flagUrl = "https://flagcdn.com/w320/tc.png"),
        JCountryListType.JCountry(alpha2 = "TV", alpha3 = "TUV", countryCode = "+688", countryName = "Tuvalu", flagUrl = "https://flagcdn.com/w320/tv.png"),

        JCountryListType.JCountryFirstAlphabet("U"),
        JCountryListType.JCountry(alpha2 = "UG", alpha3 = "UGA", countryCode = "+256", countryName = "Uganda", flagUrl = "https://flagcdn.com/w320/ug.png"),
        JCountryListType.JCountry(alpha2 = "UA", alpha3 = "UKR", countryCode = "+380", countryName = "Ukraine", flagUrl = "https://flagcdn.com/w320/ua.png"),
        JCountryListType.JCountry(alpha2 = "AE", alpha3 = "ARE", countryCode = "+971", countryName = "United Arab Emirates", flagUrl = "https://flagcdn.com/w320/ae.png"),
        JCountryListType.JCountry(alpha2 = "GB", alpha3 = "GBR", countryCode = "+44", countryName = "United Kingdom", flagUrl = "https://flagcdn.com/w320/gb.png"),
        JCountryListType.JCountry(alpha2 = "US", alpha3 = "USA", countryCode = "+1", countryName = "United States", flagUrl = "https://flagcdn.com/w320/us.png"),
        JCountryListType.JCountry(alpha2 = "UY", alpha3 = "URY", countryCode = "+598", countryName = "Uruguay", flagUrl = "https://flagcdn.com/w320/uy.png"),
        JCountryListType.JCountry(alpha2 = "UZ", alpha3 = "UZB", countryCode = "+998", countryName = "Uzbekistan", flagUrl = "https://flagcdn.com/w320/uz.png"),

        JCountryListType.JCountryFirstAlphabet("V"),
        JCountryListType.JCountry(alpha2 = "VU", alpha3 = "VUT", countryCode = "+678", countryName = "Vanuatu", flagUrl = "https://flagcdn.com/w320/vu.png"),
        JCountryListType.JCountry(alpha2 = "VA", alpha3 = "VAT", countryCode = "+39", countryName = "Vatican City", flagUrl = "https://flagcdn.com/w320/va.png"),
        JCountryListType.JCountry(alpha2 = "VE", alpha3 = "VEN", countryCode = "+58", countryName = "Venezuela", flagUrl = "https://flagcdn.com/w320/ve.png"),
        JCountryListType.JCountry(alpha2 = "VN", alpha3 = "VNM", countryCode = "+84", countryName = "Vietnam", flagUrl = "https://flagcdn.com/w320/vn.png"),

        JCountryListType.JCountryFirstAlphabet("W"),
        JCountryListType.JCountry(alpha2 = "WF", alpha3 = "WLF", countryCode = "+681", countryName = "Wallis and Futuna", flagUrl = "https://flagcdn.com/w320/wf.png"),
        JCountryListType.JCountry(alpha2 = "EH", alpha3 = "ESH", countryCode = "+212", countryName = "Western Sahara", flagUrl = "https://flagcdn.com/w320/eh.png"),

        JCountryListType.JCountryFirstAlphabet("Y"),
        JCountryListType.JCountry(alpha2 = "YE", alpha3 = "YEM", countryCode = "+967", countryName = "Yemen", flagUrl = "https://flagcdn.com/w320/ye.png"),

        JCountryListType.JCountryFirstAlphabet("Z"),
        JCountryListType.JCountry(alpha2 = "ZM", alpha3 = "ZMB", countryCode = "+260", countryName = "Zambia", flagUrl = "https://flagcdn.com/w320/zm.png"),
        JCountryListType.JCountry(alpha2 = "ZW", alpha3 = "ZWE", countryCode = "+263", countryName = "Zimbabwe", flagUrl = "https://flagcdn.com/w320/zw.png")
    )

}